### ISSUE TITLE
There's a new version of open5gs, open5gs_ Is there any new change in config?

### ISSUE THREAD

**Issue by kuanghanqian** [herlesupreeth/Open5gs_Config#1]
hi, @herlesupreeth , Thanks a lot.
The following error occurred in UE connection:

tail -f /var/log/syslog
Sep 16 06:20:55 khq rc.local[940]: #033[32m09/16 06:20:55.191#033[0m: [#033[33mmme#033[0m] #033[1;32mINFO#033[0m: [Removed] Number of MME-Sessions is now 0 (../src/mme/mme-context.c:3330)
Sep 16 06:20:55 khq rc.local[940]: #033[32m09/16 06:20:55.720#033[0m: [#033[33mmme#033[0m] #033[1;32mINFO#033[0m: [Removed] Number of eNB-UEs is now 0 (../src/mme/mme-context.c:3318)
Sep 16 06:20:58 khq /usr/local/sbin/kamailio[2879]: INFO: cdp [peerstatemachine.c:524]: I_Snd_Conn_Req(): I_Snd_Conn_Req(): Peer hss.ims.mnc012.mcc454.3gppnetwork.org
Sep 16 06:20:58 khq /usr/local/sbin/kamailio[2879]: INFO: cdp [receiver.c:874]: peer_connect(): peer_connect(): Trying to connect to 192.168.4.107 port 3868
Sep 16 06:20:58 khq /usr/local/sbin/kamailio[2879]: ERROR: cdp [receiver.c:922]: peer_connect(): peer_connect(): Error opening connection to to 192.168.4.107 port 3868 >Connection refused
Sep 16 06:21:02 khq /usr/local/sbin/kamailio[2708]: DEBUG: ims_dialog [dlg_handlers.c:1923]: print_all_dlgs(): ********************
Sep 16 06:21:02 khq /usr/local/sbin/kamailio[2708]: DEBUG: ims_dialog [dlg_handlers.c:1924]: print_all_dlgs(): printing 4096 dialogs
Sep 16 06:21:02 khq /usr/local/sbin/kamailio[2708]: DEBUG: ims_dialog [dlg_handlers.c:1934]: print_all_dlgs(): ********************
Sep 16 06:21:02 khq /usr/local/sbin/kamailio[2708]: DEBUG: ims_auth [authorize.c:187]: reg_await_timer(): Looking for expired/useless at 25297713

**Comment by herlesupreeth** [comment]
I havent used the latest open5gs repo. The configs here are only for tag v1.3.0

**Comment by kuanghanqian** [comment]
@herlesupreeth ,  
I'm sorry to disturb you ，What is the reason for this mistake? Thanks a lot!

![image](https://user-images.githubusercontent.com/69032320/93958469-21584000-fd89-11ea-927b-5b223d1ce96e.png)

**Comment by herlesupreeth** [comment]
Either the pcrf is not connected to pcscf or the ip in AAR request message from pcscf to pcrf is not having a gx session in pcrf. If you send me a pcap i can tell more clearly

**Comment by kuanghanqian** [comment]
> Either the pcrf is not connected to pcscf or the ip in AAR request message from pcscf to pcrf is not having a gx session in pcrf. If you send me a pcap i can tell more clearly

Thank you! The problem has been solved,
