### ISSUE TITLE
I have an error when run srsenb with this repos

### ISSUE THREAD

**Issue by sajem2020** [herlesupreeth/Open5gs_Config#10]
I have used mme.yaml config. could you help me how can I set srsenb.conf with this config.
I have changed ens3 to enp3s0 (my ethernet) but I dont know how to change sesenb.conf.
I dont have error with this config:
[enb.zip](https://github.com/herlesupreeth/Open5gs_Config/files/6070413/enb.zip)
[mme.zip](https://github.com/herlesupreeth/Open5gs_Config/files/6070416/mme.zip)
but 
 s1ap:
      - addr: 127.0.0.2
    gtpc:
      dev: enp3s0
is difference with your config
    s1ap:
      dev: ens3
    gtpc:
      dev: ens3
I want to run ims volte but I have an error in pcscf
my output are:
[hss.zip](https://github.com/herlesupreeth/Open5gs_Config/files/6070448/hss.zip)
[icscf.zip](https://github.com/herlesupreeth/Open5gs_Config/files/6070449/icscf.zip)
[pcrf.zip](https://github.com/herlesupreeth/Open5gs_Config/files/6070450/pcrf.zip)
[pcscf.zip](https://github.com/herlesupreeth/Open5gs_Config/files/6070451/pcscf.zip)
[scscf.zip](https://github.com/herlesupreeth/Open5gs_Config/files/6070452/scscf.zip)

please help me

**Comment by herlesupreeth** [comment]
I dont see any error in PCSCF, the ERROR logs use see related to NAT ping in PCSCF is a mistake in logging level, causing it to output to console with error level.
