### ISSUE TITLE
enb config for this core config

### ISSUE THREAD

**Issue by faratell** [herlesupreeth/Open5gs_Config#11]
Hello.
I have installed open5gs tags/v2.6.6 on ubuntu 22.04 and in the same machine have installed srsran for enb. 
I use your confi for open5gs. what should be set for this configuration in enb.conf?
mme_addr =?
gtp_bind_addr = ?
s1c_bind_addr = ?

**Comment by faratell** [comment]
Also when using the rb.conf you commented on https://github.com/srsran/srsRAN_4G/issues/435#issuecomment-581975418 , 
have this error while running end.
Error section five_qi_config not found.
Optional 5G SRB configuration is not supported yet.
Please specify 5G SRB1 and SRB2 configuration.
Error parsing RB configuration

what should the rb config be set?

**Comment by faratell** [comment]
can anyone help me for this problem? I am waiting for your answer.

**Comment by herlesupreeth** [comment]
Please use the configuration files below as a reference

https://github.com/herlesupreeth/docker_open5gs/blob/master/srslte/enb.conf
https://github.com/herlesupreeth/docker_open5gs/blob/master/srslte/rr.conf
https://github.com/herlesupreeth/docker_open5gs/blob/master/srslte/rb.conf

**Comment by faratell** [comment]
Many thanks for your help. I have installed srsRAN version 23.04. Is it ok for this configuration?
on enb config, according to your mme and sgw config, I set :
mme_addr = 127.0.0.2
gtp_bind_addr = 127.0.0.3
s1c_bind_addr = 127.0.0.3
But also have Failed to initiate S1 connection.
I have installed srsRAN and open5gs on the same machine and use config as you said (unless change mnc, mcc, interface name, and sip address).

**Comment by faratell** [comment]
I would be very grateful if you could guide me in this regard as soon as possible.

**Comment by faratell** [comment]
I installed open5gs and srsRAN on same machine with ip address 192.168.75.185. when I set this ip :
mme_addr = 192.168.75.185
gtp_bind_addr = 192.168.75.185
s1c_bind_addr = 192.168.75.185
 and run enb, show this error:
 Failed to bind on address 192.168.75.185, port 2152: Address already in use
Error initializing EUTRA stack.
and in mme.log show :
02/14 13:50:09.666: [mme] INFO: eNB-S1 accepted[192.168.75.185]:44311 in s1_path module (../src/mme/s1ap-sctp.c:114)
02/14 13:50:09.666: [mme] INFO: eNB-S1 accepted[192.168.75.185] in master_sm module (../src/mme/mme-sm.c:108)
02/14 13:50:09.666: [mme] INFO: [Added] Number of eNBs is now 1 (../src/mme/mme-context.c:2557)
02/14 13:50:09.666: [mme] INFO: eNB-S1[192.168.75.185] max_num_of_ostreams : 30 (../src/mme/mme-sm.c:150)
02/14 13:50:14.342: [mme] INFO: eNB-S1[192.168.75.185] connection refused!!! (../src/mme/mme-sm.c:166)
02/14 13:50:14.342: [mme] INFO: [Removed] Number of eNBs is now 0 (../src/mme/mme-context.c:2591)

when I run:
sudo netstat -tulnlp | grep 2152
udp        0      0 192.168.75.185:2152     0.0.0.0:*                           78184/./install/bin 
cat /proc/78184/comm
open5gs-sgwud

when i stop open5gs-sgwud enb run correctly and connected to mme. But now i can not run sgwu.
 ERROR: socket bind(2) [192.168.75.185]:2152 failed (98:Address already in use) (../lib/core/ogs-socket.c:114)
02/14 15:43:48.464: [sock] ERROR: udp_server() [192.168.75.185]:2152 failed (98:Address already in use) (../lib/core/ogs-udp.c:67)
02/14 15:43:48.464: [app] ERROR: Failed to intialize SGW-U (../src/sgwu/app.c:28)
02/14 15:43:48.464: [app] FATAL: Open5GS initialization failed. Aborted (../src/main.c:219)
root@faraz:~/open5gs# 


how can i solve it?

**Comment by faratell** [comment]
can use help me to how solve this issue?

**Comment by herlesupreeth** [comment]
You cannot use that IP on eNB, you may want to use the following settings

mme_addr = 192.168.75.185
gtp_bind_addr = 127.0.0.100
s1c_bind_addr = 127.0.0.100

**Comment by faratell** [comment]
Are you sure  127.0.0.100 is the true address for gtp_bind_addr according to your config in this repository?
Also with this config I have this error:
Failed to initiate S1 connection. Attempting reconnection in 10 seconds

**Comment by faratell** [comment]
Hello. hope you are fine. I upload my all config files.
[configs.zip](https://github.com/herlesupreeth/Open5gs_Config/files/14322422/configs.zip)
i run as bellow sequence
HSS → MME → PCRF → PGW → SGW →eNB→  P-CSCF → I-CSCF → S-CSCF → FHoSS
But enb failed to  initiate S1 connection.
Also i have this error when run  P-CSCF:
0(376889) ERROR: ims_ipsec_pcscf [ipsec.c:652]: clean_sa(): Error sending delete SAs command via netlink socket: No data available
 0(376889) WARNING: ims_ipsec_pcscf [cmd.c:1352]: ipsec_cleanall(): Error cleaning IPSec Security associations during startup.
 0(376889) ERROR: ims_ipsec_pcscf [ipsec.c:701]: clean_policy(): Error sending delete policies command via netlink socket: No data available
 0(376889) WARNING: ims_ipsec_pcscf [cmd.c:1356]: ipsec_cleanall(): Error cleaning IPSec Policies during startup.
 0(376889) INFO: ims_registrar_pcscf [ims_registrar_pcscf_mod.c:308]: mod_init(): Successfully bound to PCSCF IPSEC module
 0(376889) INFO: <core> [main.c:3232]: main(): processes (at least): 112 - shm size: 67108864 - pkg size: 8388608
 0(376889) WARNING: tm [tm.c:550]: fixup_routes(): t_on_failure("NATMANAGE"): empty/non existing route
6(377056) ERROR: cdp [receiver.c:1060]: peer_connect(): peer_connect(): Error opening connection to to 127.0.0.5 port 3868 >Connection refused
95(377055) INFO: cdp [tcp_accept.c:197]: accept_connection(): accept_connection(): new tcp connection accepted!
93(377053) INFO: cdp [receiver.c:193]: add_serviced_peer(): add_serviced_peer(): Adding serviced_peer_t to receiver for peer []
93(377053) INFO: cdp [receiver.c:258]: drop_serviced_peer(): drop_serviced_peer(): Dropping serviced_peer_t from receiver for peer [pcrf.epc.mnc55.mcc999.farazNET.org]
98(377067) ERROR: <script>: Preloading NAT-PING. Rows: 0

and when run scscf:
26(278634) INFO: cdp [receiver.c:193]: add_serviced_peer(): add_serviced_peer(): Adding serviced_peer_t to receiver for peer [hss.ims.mnc55.mcc999.farazNET.org]
26(278634) INFO: cdp [receiver.c:487]: receiver_process(): receiver_process(): [hss.ims.mnc55.mcc999.farazNET.org] Receiver process starting up...
28(278636) INFO: cdp [peerstatemachine.c:549]: I_Snd_Conn_Req(): I_Snd_Conn_Req(): Peer hss.ims.mnc55.mcc999.farazNET.org 
28(278636) INFO: cdp [receiver.c:1002]: peer_connect(): peer_connect(): Trying to connect to 192.168.75.185 port 3868
28(278636) ERROR: cdp [receiver.c:1060]: peer_connect(): peer_connect(): Error opening connection to to 192.168.75.185 port 3868 >Connection refused

and when run icscf:

28(377226) INFO: cdp [receiver.c:1002]: peer_connect(): peer_connect(): Trying to connect to 192.168.75.185 port 3868

I would very appreciate it if you help me as soon as possible. I have spent a lot of time in this regard and I need to accomplish it.

**Comment by herlesupreeth** [comment]
Are you setting the correct IP for mme_addr ? is the IP address of enp0s31f6 interface 192.168.75.185 ?

**Comment by herlesupreeth** [comment]
> 6(377056) ERROR: cdp [receiver.c:1060]: peer_connect(): peer_connect(): Error opening connection to to 127.0.0.5 port 3868 >Connection refused

The IP address of PCRF used by P-CSCF is wrong for diameter connection. It should be 127.0.0.9 as per your pcrf.yaml

**Comment by faratell** [comment]
> Are you setting the correct IP for mme_addr ? is the IP address of enp0s31f6 interface 192.168.75.185 ?

yes. I installed open5gs,IMS and eNB all in same machine which has this ifconfig:

ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:e7:d1:7d:fa  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp0s31f6: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.75.185  netmask 255.255.255.0  broadcast 192.168.75.255
        inet6 fe80::2e4d:54ff:fee8:c660  prefixlen 64  scopeid 0x20<link>
        ether 2c:4d:54:e8:c6:60  txqueuelen 1000  (Ethernet)
        RX packets 3870  bytes 1921227 (1.9 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3245  bytes 670138 (670.1 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16  memory 0xf7400000-f7420000  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 725  bytes 74708 (74.7 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 725  bytes 74708 (74.7 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ogstun: flags=4241<UP,POINTOPOINT,NOARP,MULTICAST>  mtu 1400
        inet 192.168.100.1  netmask 255.255.255.0  destination 192.168.100.1
        inet6 fd84:6aea:c36e:2b69::  prefixlen 48  scopeid 0x0<global>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ogstun2: flags=4241<UP,POINTOPOINT,NOARP,MULTICAST>  mtu 1400
        inet 192.168.101.1  netmask 255.255.255.0  destination 192.168.101.1
        inet6 fd1f:76f3:da9b:101::  prefixlen 48  scopeid 0x0<global>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
        ether 52:54:00:8e:fe:8f  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by faratell** [comment]
> > 6(377056) ERROR: cdp [receiver.c:1060]: peer_connect(): peer_connect(): Error opening connection to to 127.0.0.5 port 3868 >Connection refused
> 
> The IP address of PCRF used by P-CSCF is wrong for diameter connection. It should be 127.0.0.9 as per your pcrf.yaml

where it should be set?
this is my pcscf config in /etc/kamailio_pcscf folder. what should be change?
[pcscf.zip](https://github.com/herlesupreeth/Open5gs_Config/files/14329097/pcscf.zip)

**Comment by faratell** [comment]
in https://github.com/open5gs/open5gs/issues/344 you say This error you can ignore, its harmless. is it true?
How can config srsran to initiate s1 connection?

**Comment by herlesupreeth** [comment]
I would suggest changing as follows

gtp_bind_addr = 127.0.0.1
s1c_bind_addr = 127.0.0.1

**Comment by faratell** [comment]
I change the enb.conf as you mentioned but also have error on s1 connection.
Also I have this warninig on sgwc.yaml:
02/24 13:26:23.779: [pfcp] WARNING: [1] LOCAL  No Reponse. Give up! for step 1 type 5 peer [127.0.0.6]:8805 (../lib/pfcp/xact.c:599)
02/24 13:26:27.274: [sgwc] WARNING: Retry to association with peer [127.0.0.6]:8805 failed (../src/sgwc/pfcp-sm.c:106)
02/24 13:26:28.272: [sgwc] INFO: PFCP associated [127.0.0.6]:8805 (../src/sgwc/pfcp-sm.c:183)
02/24 13:26:29.776: [sgwc] WARNING: PFCP[RSP] has already been associated [127.0.0.6]:8805 (../src/sgwc/pfcp-sm.c:284)
 
Is it important?
I installed all kamailio aip, open5gs and enb on the same machine without any wirtualization.
do you recommend to solve this problem, install open5gs and sip server on a virtual machine  ?

**Comment by faratell** [comment]
I installed open5gs and ims on a vm. It correctly connected to RAN (which is installed in host OS). My problem is solved.
