### ISSUE TITLE
Config not compatible with latest version of Open5gs

### ISSUE THREAD

**Issue by BorjanEch0** [herlesupreeth/Open5gs_Config#2]
Dear Developer.

Is there a chance that you can upload the configs for volte on the latest open5gs version?

Thanks in advance

**Comment by herlesupreeth** [comment]
Thank you @BorjanEch0 for bringing this up. Its on my todo list..will update it soon

**Comment by herlesupreeth** [comment]
I have updated the config files as per the latest release of open5gs, please try it out and let me know if that works for you

**Comment by BorjanEch0** [comment]
Thank you for this kindness, i will check today and let you know if the test passes.

**Comment by BorjanEch0** [comment]
i had to make some changes to the files including the freediameter library path, and ip addresses/ip interfaces and i also had to add smf as an entry to the ims zone in bind and also in smf.yaml i had to add the server ip as the dns server for bind to resolve ims address on UE. so far lte data works but volte is still not seen as an option, will feedback again.
