### ISSUE TITLE
VER

### ISSUE THREAD

**Issue by ghost** [herlesupreeth/Open5gs_Config#3]

**Comment by herlesupreeth** [comment]
sure, will do

**Comment by herlesupreeth** [comment]
done, you can find the branch with name 4g containing the configs related to v1.3.0 of open5gs

**Comment by ghost** [comment]
Thanks,
Are u gonna change the Open5Gs Volte instruction in near future?

**Comment by herlesupreeth** [comment]
you mean for the new open5gs 4g-5g core? havent thought about it..but should do at some point..On the contrary, i would rather update the guide to use https://github.com/herlesupreeth/docker_open5gs repo for easier setup

**Comment by ghost** [comment]
Yea, I meant that.
That would be much appreciated if u do so, I don't think it takes much times!

Docker is easier but if someone wants to change some part of the code for some specific usage, the OpenStack  implementation would be better 

Thanks in advance
