### ISSUE TITLE
eNB configs for VOLTE in OpenStack

### ISSUE THREAD

**Issue by ghost** [herlesupreeth/Open5gs_Config#4]
Dear @herlesupreeth 

Hi,

I followed ur great instruction on VOLTE using OPENSTACK.
So Now i have VOLTE AND CORE on openstack VM, All components are connected and running including pcscf, scscf, icscf, FOHSS, PCRF, MME, HSS, SGW, PGW on single OPENSTACK VM

So now i want to connect VOLTE and Core to eNB which is SRSLTE
For eNB i decided to run SRSLTE on my own PC which doesn't have OpenStack and its Native Ubuntu!

I installed the eNB cut i do not have any idea how to connect eNB to MME and other components including sgw, because eNB is on native ubuntu PC and CORE components are on single OPENSTACK instance!

I mean eNB has 192.168.100.50 ip addr.    but for example MME has 127.0.0.2 on Openstack with 192.168.100.197 floating Ip address and 10.4.128.21 for local openstack instance addr.! 
I don't have any idea on how to connect these to together!
Do you have eNB config file example ? that would be much appreciated

Could u please guide me on that?

Thanks 
Best regards

**Comment by herlesupreeth** [comment]
For connecting eNb to EPC + IMS, modify the following parameters of enb.conf

mme_addr = 192.168.100.197
gtp_bind_addr = 192.168.100.50
s1c_bind_addr = 192.168.100.50

and in drb.conf have the following configuration

```

// All times are in ms. Use -1 for infinity, where available

qci_config = (

{
  qci=1;
  pdcp_config = {
    discard_timer = 100;                
    pdcp_sn_size = 12;                  
  }
  rlc_config = {
    ul_um = {
      sn_field_length = 10; 
    };
    dl_um = {
      sn_field_length = 10;
      t_reordering    = 50;
    };
  };
  logical_channel_config = {
    priority = 6; 
    prioritized_bit_rate   = -1; 
    bucket_size_duration  = 100; 
    log_chan_group = 1; 
  };
},
{
  qci=5;
  pdcp_config = {
    discard_timer = -1;
    status_report_required = true;
  }
  rlc_config = {
    ul_am = {
      t_poll_retx = 80;
      poll_pdu = 128;
      poll_byte = 125;
      max_retx_thresh = 4;
    };
    dl_am = {
      t_reordering = 80;
      t_status_prohibit = 60;
    };
  };
  logical_channel_config = {
    priority = 11; 
    prioritized_bit_rate   = -1; 
    bucket_size_duration  = 100; 
    log_chan_group = 2; 
  };
},
{
  qci=7;
  pdcp_config = {
    discard_timer = 100;                
    pdcp_sn_size = 12;                  
  }
  rlc_config = {
    ul_um = {
      sn_field_length = 10; 
    };
    dl_um = {
      sn_field_length = 10; 
      t_reordering    = 45;             
    };
  };
  logical_channel_config = {
    priority = 13; 
    prioritized_bit_rate   = -1; 
    bucket_size_duration  = 100; 
    log_chan_group = 2; 
  };
},
{
  qci=9;
  pdcp_config = {
    discard_timer = -1;
    status_report_required = true;
  }
  rlc_config = {
    ul_am = {
      t_poll_retx = 120;
      poll_pdu = 64;
      poll_byte = 750;
      max_retx_thresh = 16;
    };
    dl_am = {
      t_reordering = 50;
      t_status_prohibit = 50;
    };
  };
  logical_channel_config = {
    priority = 11; 
    prioritized_bit_rate   = -1; 
    bucket_size_duration  = 100; 
    log_chan_group = 3; 
  };
}

);

```

Finally, in sgw.yaml, have the following parameter set as follows under gtpu section
```

sgw:
    gtpc:
      addr: 127.0.0.2
    gtpu:
      dev: ens3
      advertise_addr: 192.168.100.197

```

**Comment by ghost** [comment]
Thank You so much

i have another question which will ask in the next issue
