### ISSUE TITLE
Could you shared your IPv6 config ?

### ISSUE THREAD

**Issue by alf-askey** [herlesupreeth/Open5gs_Config#9]
Hi herlesupreeth,

Could you shared your IPv6 config ? 

because  my phone can get IPv4/IPv6 address

from ogstun interface ping phone IPv4 --> pass
from ogstun interface ping phone IPv6 --> fail

i check GTP ,icmp packet will over GTP , but icmpv6 have no passthrouh  GTP

[IPv6 ping fail.zip](https://github.com/herlesupreeth/Open5gs_Config/files/5916188/IPv6.ping.fail.zip)

**Comment by herlesupreeth** [comment]
Thanks for bringing this up. Unfortunately, IPv6 on docker/docker-compose is quite a bit of mess. I have some work done on a local version of my machine but haven't had time to test or develop it further.

**Comment by herlesupreeth** [comment]
Sorry, i misread your question under wrong repository. I would suggest to remove the following lines in each of the component's .yaml file and give it a try

```
     no_ipv6: true
     prefer_ipv4: true
```

**Comment by alf-askey** [comment]
If I do not use docker to install open5gs,i use physical macchine to install open5gs, how can IPv6 passthrough GTP?
which other items do I miss?
1) config smf.cfg
2) add routing table
3) add ip6tables table

**Comment by herlesupreeth** [comment]
> config smf.cfg
> add routing table

Most likely not needed as the SGWU is bound to dev ens3 (interface name may vary from your setup) so it will listening on both IPv4 and IPv6 address - Assuming you are using Non-Standalone deployment/4G-5G Hybrid mode

> add ip6tables table

Yes, if you want the IPV6 traffic to be NATed to reach internet

**Comment by alf-askey** [comment]
my NIC name is internet(with IPv4/IPv6 address) , when change to dev name , it is fail([Removed] Number of UPF-sessions is now 1), 
so  if i wanna IPv6 address  passthrough GTP , i need to config GTP address is IPv6 ?

sgwu:
gtpu:
- dev: internet
pfcp:
- addr: 127.0.0.6

gtpu_baseon dev name.zip

log as the below
02/03 09:12:05.618: [mme] INFO: Initial UE Message (../src/mme/s1ap-handler.c:223)
02/03 09:12:05.618: [mme] INFO: [Added] Number of eNB-UEs is now 1 (../src/mme/mme-context.c:3295)
02/03 09:12:05.618: [mme] INFO: ENB_UE_S1AP_ID[82] MME_UE_S1AP_ID[34] TAC[108] CellID[0xd4] (../src/mme/s1ap-handler.c:360)
02/03 09:12:05.618: [mme] INFO: [001010000000013] known UE by IMSI (../src/mme/mme-context.c:2396)
02/03 09:12:05.618: [emm] WARNING: Attach request[001010000000013] (../src/mme/emm-sm.c:918)
02/03 09:12:05.618: [emm] INFO: IMSI[001010000000013] (../src/mme/emm-handler.c:172)
02/03 09:12:05.620: [upf] INFO: [Removed] Number of UPF-sessions is now 1 (../src/upf/context.c:475)
02/03 09:12:05.620: [smf] INFO: Removed Session: UE IMSI:[001010000000013] DNN:[internet] IPv4:[10.45.0.32] IPv6:[cafe::d] (../src/smf/context.c:1119)
02/03 09:12:05.620: [smf] INFO: [Removed] Number of SMF-Sessions is now 1 (../src/smf/context.c:2145)
02/03 09:12:05.620: [smf] INFO: [Removed] Number of SMF-UEs is now 1 (../src/smf/context.c:587)
02/03 09:12:05.620: [sgwu] INFO: [Removed] Number of SGWU-sessions is now 1 (../src/sgwu/context.c:459)
02/03 09:12:05.620: [sgwc] INFO: [Removed] Number of SGWC-Sessions is now 1 (../src/sgwc/context.c:988

**Comment by alf-askey** [comment]
mybe this is my small cell issue .
may i ask you , if  UE need IPv4 /IPv6 dual statck , i must setup gtpu with IPv4 and IPv6

**Comment by herlesupreeth** [comment]
For dual stack you should setup gtpu with IPv4 and IPv6. And also the for your eNB

**Comment by alf-askey** [comment]
thank your help, i got it
when (corenetwork / eNB)'s gtpu only config IPv4 address 
if  smf assign IPv4/IPv6 to phone(UE) ,  IPv4 can passthrouh GTP , but does IPv6 can also passthrouh GTP ?

**Comment by alf-askey** [comment]
IPv6 can over GTP , but i cannot ping my phone IPv6 from ogstun
which steps i need to check ? do you have  andy suggestion ?
![IPv6 over GTP](https://user-images.githubusercontent.com/67717964/106739701-6607b800-6654-11eb-987a-c79027ce52aa.png)

**Comment by alf-askey** [comment]
this is my  IPv6 routing table

root@csit:~# ip -6 r
cafe::/64 dev ogstun metric 1 pref medium
cafe::/64 dev internet proto kernel metric 256 pref medium
cafe::/64 dev ogstun proto kernel metric 256 pref medium
fe80::/64 dev internet proto kernel metric 256 pref medium
fe80::/64 dev ogstun proto kernel metric 256 pref medium

**Comment by alf-askey** [comment]
i found that core network assgin statefull IPv6 address to UE , but UE get stateless IPaddess

**Comment by herlesupreeth** [comment]
Have you enabled the ipv6 forwarding? If not i would suggest to enable it and give it a try

**Comment by herlesupreeth** [comment]
Please post the answer if you are able to solve this issue as it could help other. Also, please close the issue if you have solved it

**Comment by herlesupreeth** [comment]
Closing this issue because open5gs supports IPv6 so if IPv6 does not work then its a matter of configuring the host networking or testbed network

**Comment by alf-askey** [comment]
hi herlesupreeth,
                           sorry i forgot to close this issue, sorry ! , next time i will closed it

**Comment by alf-askey** [comment]
but my IPv6 topology still issue , i will follow your commend to try it , paste my config  when  done
